# Generated by Django 4.2.7 on 2026-04-25 12:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_product_batch_number_product_expiry_date_and_more'),
        ('users', '0006_dealerprofile_business_email_dealerprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('overstocked', 'Overstocked'), ('slow_moving', 'Slow Moving'), ('dead_stock', 'Dead Stock')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('A', 'A - High Value (70% revenue, 20% items)'), ('B', 'B - Medium Value (20% revenue, 30% items)'), ('C', 'C - Low Value (10% revenue, 50% items)')], max_length=1)),
                ('annual_demand', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('annual_consumption_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reorder_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reorder_point', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('safety_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_time_days', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)])),
                ('inventory_turnover', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('days_inventory_outstanding', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abc_analyses', to='users.dealerprofile')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abc_analysis', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'ABC Analyses',
                'ordering': ['classification', '-annual_consumption_value'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('historical_avg_demand', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('forecasted_demand', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('forecasted_demand_upper', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('forecasted_demand_lower', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('alpha', models.DecimalField(decimal_places=2, default=Decimal('0.3'), max_digits=3)),
                ('mae', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('training_data_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='users.dealerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dss_forecasts', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Forecasts',
                'ordering': ['-updated_at'],
                'unique_together': {('product', 'dealer', 'period_type')},
            },
        ),
    ]
