# Generated by Django 4.2.7 on 2026-04-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('new_order', 'New Order'), ('payment_confirmed', 'Payment Confirmed'), ('order_shipped', 'Order Shipped'), ('system', 'System Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('reference_id', models.CharField(blank=True, help_text='Order ID, Product ID, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.dealerprofile')),
            ],
            options={
                'db_table': 'dealer_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
