# Generated by Django 4.2.7 on 2026-04-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_rating_product_review_count'),
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('reorder_quantity', models.PositiveIntegerField(default=50)),
                ('last_stock_update', models.DateTimeField(auto_now=True)),
                ('last_reordered', models.DateTimeField(blank=True, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='users.dealerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_inventories', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Dealer Inventories',
                'ordering': ['product__name'],
                'unique_together': {('dealer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='DecisionSupportMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('demand_forecast', 'Demand Forecast'), ('inventory_turnover', 'Inventory Turnover Rate'), ('profit_margin', 'Profit Margin Analysis'), ('customer_trend', 'Customer Buying Trends'), ('seasonal_pattern', 'Seasonal Pattern'), ('bestseller_analysis', 'Bestseller Analysis')], max_length=30)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metric_label', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('period_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trend_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_metrics', to='users.dealerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Decision Support Metrics',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('sale', 'Sale'), ('return', 'Return'), ('damage', 'Damaged')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, help_text='Order ID, Invoice, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dealer.dealerinventory')),
            ],
            options={
                'verbose_name': 'Dealer Stock Movement',
                'verbose_name_plural': 'Dealer Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_inventory_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_stock_count', models.PositiveIntegerField(default=0)),
                ('out_of_stock_count', models.PositiveIntegerField(default=0)),
                ('unique_customers', models.PositiveIntegerField(default=0)),
                ('returning_customers', models.PositiveIntegerField(default=0)),
                ('top_products', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.dealerprofile')),
            ],
            options={
                'verbose_name_plural': 'Dealer Reports',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='DealerSalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unique_customers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='users.dealerprofile')),
            ],
            options={
                'verbose_name_plural': 'Dealer Sales Analytics',
                'ordering': ['-date'],
                'unique_together': {('dealer', 'date')},
            },
        ),
    ]
