# Generated by Django 4.2.7 on 2026-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_dealer_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Product batch/lot number', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiration date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
