# Generated by Django 4.2.7 on 2026-04-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_forecast_abcresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abcresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['-forecast_date']},
        ),
        migrations.AlterUniqueTogether(
            name='abcresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='abcresult',
            name='classification',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='abcresult',
            name='cumulative_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='abcresult',
            name='period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='abcresult',
            name='period_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='abcresult',
            name='sales_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='alpha',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='abcresult',
            table=None,
        ),
        migrations.AlterModelTable(
            name='forecast',
            table=None,
        ),
    ]
