# Generated by Django 4.2.7 on 2026-04-17 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('total_points_redeemed', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyalty Account',
                'verbose_name_plural': 'Loyalty Accounts',
                'db_table': 'loyalty_accounts',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Glow Beyond Rewards', max_length=200)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1.0, help_text='Points earned per currency unit spent', max_digits=5)),
                ('currency_value_per_point', models.DecimalField(decimal_places=2, default=0.01, help_text='Currency value of each point', max_digits=5)),
                ('signup_bonus', models.PositiveIntegerField(default=100, help_text='Bonus points for new members')),
                ('referral_bonus', models.PositiveIntegerField(default=50, help_text='Bonus points for referrals')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
                'db_table': 'loyalty_programs',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points_required', models.PositiveIntegerField()),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=9999, help_text='Unlimited if 9999')),
                ('image', models.ImageField(blank=True, null=True, upload_to='loyalty_rewards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loyalty Reward',
                'verbose_name_plural': 'Loyalty Rewards',
                'db_table': 'loyalty_rewards',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('bonus', 'Bonus'), ('refunded', 'Refunded'), ('expired', 'Expired')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for earned, negative for redeemed')),
                ('description', models.TextField()),
                ('reference_id', models.CharField(blank=True, help_text='Order ID or other reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
            ],
            options={
                'verbose_name': 'Loyalty Transaction',
                'verbose_name_plural': 'Loyalty Transactions',
                'db_table': 'loyalty_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltyaccount')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltyreward')),
            ],
            options={
                'verbose_name': 'Loyalty Redemption',
                'verbose_name_plural': 'Loyalty Redemptions',
                'db_table': 'loyalty_redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
