# Generated by Django 4.2.7 on 2026-04-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_options_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Movement', 'verbose_name_plural': 'Inventory Movements'},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.IntegerField(blank=True, help_text='Stock level after this movement', null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.IntegerField(blank=True, help_text='Stock level before this movement', null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('sale', 'Sale')], max_length=20),
        ),
    ]
