# Generated by Django 4.2.7 on 2026-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business email for customer inquiries', max_length=254),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for customer contact', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone (shown on products)', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Business location/address', max_length=200),
        ),
    ]
