# Generated by Django 4.2.7 on 2026-04-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_429f6b_idx',
            old_name='audit_auditlog_user_id_c5c9f2_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_resourc_2a3aef_idx',
            old_name='audit_auditlog_resourc_7f2a0c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_0c6a84_idx',
            old_name='audit_auditlog_action_6c9f2e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='audit_auditlog_created_6c9f2e_idx',
        ),
    ]
